### PR TITLE
Make m_join0.cpp use /PARTALL instead of /join 0

### PR DESCRIPTION
**Pull request by KoraggKnightWolf**
The m_join0 module uses /join 0 to part all channels. This fork makes it work using the command /partall instead which is more intuitive and less likely to be used to trick newbies into parting all channels by mistake. 

Regards,

Koragg

### CODE REVIEW

**Comment by KoraggKnightWolf** [comment]
I reverted the changes to the m_join.cpp module and instead made an m_partall.cpp causing /partall to behave as /join 0 for those who might prefer it this way. Also almost no IRCd sticks to the RFC's and the changes are confirmed to work on InspIRCd 2.0.27.

Regards,

Koragg

**Comment by Robby-** [comment]
You could have just used m_alias and aliased the PARTALL command instead. Or even added PARTALL to this m_join0 module as an additional command instead of duplicating this module.

**Comment by Robby-** [comment]
This PR has become completely scuffed now.

**Comment by KoraggKnightWolf** [comment]
Closed due to my own mistake of not creating a branch for my own customizations and clogging up the PR. Sincerest apologies it was not intentional.

Regards,

Koragg

**Pull request closed without merging**
