### PR TITLE
Fix syntax notice in m_require_auth

### PR DESCRIPTION
**Pull request by MuffinMedic**
As with g-line, syntax should be in `[user@host]`, not `<nick>`

### CODE REVIEW

**Comment by SaberUK** [comment]
Why change to square brackets? They imply the parameter is optional when it is not.

**Comment by MuffinMedic** [comment]
@SaberUK Kept the same syntax as `/gline` for consistency. No objections to it being changed but it should be changed across all similar commands. gline/zline/eline/etc... Currently they all have brackets around the user identifier.

**Comment by SaberUK** [comment]
GLINE uses 

```cpp
syntax = "<ident@host> [<duration> :<reason>]";
```

**Comment by MuffinMedic** [comment]
@SaberUK Sorry about that, I was looking at `helpop`, not the actual `/gline` output. I've update the pull request accordingly.

**Comment by attilamolnar** [comment]
Please squash this into a single commit

**Comment by attilamolnar** [comment]
Thanks, merged.

**Pull request merged**
