### PR TITLE
m_rpg: fix a compiler warning

### PR DESCRIPTION
**Pull request by Techman-**

### CODE REVIEW

**Comment by attilamolnar** [comment]
@CyberBotX could you take a look at this?

**Comment by attilamolnar** [comment]
@Techman-: Can you address that please?

**Comment by Techman-** [comment]
```
04:52:31 PM	<Techman>	Address what
04:52:33 PM	<Techman>	size_t?
04:52:44 PM	<Techman>	I just used unsigned because gcc complained
```

**Comment by Techman-** [comment]
Oh, thanks for addressing this for me! I forgot about this.

**Pull request closed without merging**
